---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: apiserver
    io.kompose.service: apiserver
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apiserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: apiserver
        io.kompose.service: apiserver
    spec:
      containers:
        - image: cribl/scope-k8s-demo-apiserver
          env:
          - name: SCOPE_TAG_service
            value: apiserver
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 15
            timeoutSeconds: 5
          name: apiserver
          ports:
            - containerPort: 4000
          resources: 
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 128Mi

          securityContext:
            privileged: true
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: apiserver
  name: apiserver
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: apiserver
status:
  loadBalancer: {}
