apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-alpine
  labels:
    app.kubernetes.io/name: client-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: client-alpine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client-alpine
    spec:
      containers:
      - name: client-alpine
        image: alpine:latest
        command: [/scope/scope]
        args: ["-z", "/usr/bin/tail", "-F", "/scope/0/libscope.log"]
