---
# Source: logstream-leader/templates/secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata: 
 name: logstream-leader-config-cribl
stringData:
---
# Source: logstream-leader/templates/claims.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
spec:
  accessModes:
    - ReadWriteOnce
  
  resources:
    requests:
      storage: 20Gi
---
# Source: logstream-leader/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cribl-internal
  labels:
    helm.sh/chart: logstream-leader-2.4.3
    app.kubernetes.io/name: cribl
    app.kubernetes.io/instance: logstream-leader
    app.kubernetes.io/version: "2.4.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}

spec:
  type: ClusterIP
  ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: api
        
      - port: 10090
        targetPort: 10090
        protocol: TCP
        name: appscope
        
  selector:
    app.kubernetes.io/name: cribl
    app.kubernetes.io/instance: logstream-leader
---
# Source: logstream-leader/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cribl
  labels:
    helm.sh/chart: logstream-leader-2.4.3
    app.kubernetes.io/name: cribl
    app.kubernetes.io/instance: logstream-leader
    app.kubernetes.io/version: "2.4.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}

spec:
  type: NodePort
  ports:
      
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: api
        
        nodePort: 30004
        
      
  selector:
    app.kubernetes.io/name: cribl
    app.kubernetes.io/instance: logstream-leader
---
# Source: logstream-leader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cribl
  labels:
    app.kubernetes.io/name: cribl
    app.kubernetes.io/instance: logstream-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cribl
      app.kubernetes.io/instance: logstream-leader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cribl
        app.kubernetes.io/instance: logstream-leader
      annotations:
        appscope.dev/disable: "true"
    spec:
      initContainers:
        - name: copy-configs
          image: "busybox"
          volumeMounts:
          - name: cribl-initial-configs
            mountPath: /tmp/initial-configs
          - name: config-storage
            mountPath: /opt/cribl/config-volume
          command:
          - sh
          - -c
          - |
            #!/bin/sh
            mkdir -p /opt/cribl/config-volume/local
            tar -zxf /tmp/initial-configs/cribl-initial-configs.tgz -C /opt/cribl/config-volume/local --strip=2 
      containers:
        - name: logstream-leader
          image: "cribl/cribl:3.1.2-TC5"
          imagePullPolicy: Always
          volumeMounts:
          - name: config-storage
            mountPath: /opt/cribl/config-volume
          ports:
            - name: api
              containerPort: 9000
            - name: appscope
              containerPort: 10090
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 9000
            failureThreshold: 3
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 9000
            failureThreshold: 3
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: 1500m
              memory: 4096Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          env:
            # Self-Signed Certs
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: CRIBL_HOME
              value: "/opt/cribl"
            # Single Volume for persistents (CRIBL-3848)
            - name: CRIBL_VOLUME_DIR
              value: /opt/cribl/config-volume

      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: config-claim
        - name: cribl-initial-configs
          configMap:
            name: cribl-initial-configs
