{
 "title": "AppScope",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name, proc) (http.requests)",
     "legendFormat": "{{name}} - {{proc}}"
    }
   ]
  },
  {
   "title": "HTTP Non-2XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name, proc, http_status_code) (http.requests{http_status_code!~\"2[0-9]{2}\"})",
     "legendFormat": "{{name}} - {{proc}} - {{http_status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Client Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name, proc) (http.request_content_length)",
     "legendFormat": "{{name}} - {{proc}}"
    }
   ]
  },
  {
   "title": "HTTP Server Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name, proc) (http.response_content_length)",
     "legendFormat": "{{name}} - {{proc}}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "sum by (name, proc) (net_tx)", "legendFormat": "{{name}} - {{proc}}" }
   ]
  },
  {
   "title": "Network Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "sum by (name, proc) (net_rx)", "legendFormat": "{{name}} - {{proc}}" }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (proc_cpu_perc) by (name, proc)",
     "legendFormat": "{{name}} - {{proc}}"
    }
   ]
  },
  {
   "title": "Memory (max)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "max (proc_mem) by (name, proc)", "legendFormat": "{{name}} - {{proc}}" }
   ]
  },
  {
   "title": "File Opens",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (fs.open) by (name, proc)", "legendFormat": "{{name}} - {{proc}}" }
   ]
  },
  {
   "title": "File Closes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (fs.close) by (name, proc)", "legendFormat": "{{name}} - {{proc}}" }
   ]
  },
  {
   "title": "File Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (fs_read) by (name, proc)", "legendFormat": "{{name}} - {{proc}}" }
   ]
  },
  {
   "title": "File Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (fs_write) by (name, proc)", "legendFormat": "{{name}} - {{proc}}" }
   ]
  }
 ]
}