---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
  labels:
    app.kubernetes.io/name: redis-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-client
    spec:
      containers:
      - name: redis-client
        image: redis:7.0.7
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do redis-cli -h redis-server -p 6379 info; sleep 20; done;" ]

