---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app.kubernetes.io/name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-server
    spec:
      containers:
      - name: redis-server
        image: mbiesekcribl/redis:7.0.7
        command: [redis-server]
        args: ["--protected-mode no"]
        env:
        - name: SCOPE_SNAPSHOT_BACKTRACE
          value: "true"
        - name: SCOPE_SNAPSHOT_COREDUMP
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: redis-server
  name: redis-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis-server
